### PR TITLE
Add persist for recipe and rife models

### PR DESCRIPTION
**Pull request by ypurpl**
if you use a rife model I wanted a way to persist that on new updates. Still testing because idk how to make/edit a manifest

### CODE REVIEW

**Comment by vvirtues** [comment]
prob gonna add persist to recipe too

**Comment by vvirtues** [comment]
yea it works

**Comment by vvirtues** [comment]
so for the wiki ur files should look like this (assuming ur using scoop):
image

**Comment by Aetopia** [comment]
You would need to use symbolic links for this.
But that requires admin perms, compared to directory junctions which don't require it.

File junctions don't exist on the NTFS file system.

If you want to have persistent data, you will need to redirect Smoothie to a dedicated folder that stores the persistent content.

Though for use in the CLI, you will need to direct it to use the persistent content.

**Comment by vvirtues** [comment]
Already confirmed it works
You don't need all that

**Comment by vvirtues** [comment]
https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data

**Comment by Aetopia** [comment]
Please use the latest manifest from this repo.
It fixes Scoop defaulting to UTF-8 BOM.

**Comment by vvirtues** [comment]
is it not the same with the exception of my changes?

**Comment by Aetopia** [comment]
Merged 👍🏼

**Pull request merged**
